pipeline {
    agent any

    options {
        timestamps()
    }

    environment {
        LAB2_DIR = "${WORKSPACE}/lab2"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install dependencies') {
            steps {
                sh '''
                    python3 -m pip install --upgrade pip
                    python3 -m pip install -r lab2/requirements.txt
                '''
            }
        }
    }

    post {
        success {
            echo 'Конвейер lab2 завершён успешно.'
        }
        failure {
            echo 'Конвейер lab2 завершился с ошибкой.'
        }
    }
}
